version: "3"
services: 
  web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - "3000:3000"
    command: npm run start
    links: 
      - elasticsearch
      - mongo
    depends_on: 
      - mongo
      - elasticsearch
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
volumes:
  esdata: